#!/bin/sh

# cumtos ntp
uci delete system.ntp.server
uci add_list system.ntp.server='ntp.aliyun.com'
uci add_list system.ntp.server='time1.cloud.tencent.com'
uci add_list system.ntp.server='time.ustc.edu.cn'
uci add_list system.ntp.server='cn.pool.ntp.org'
# uci set system.ntp.enable_server='1'
uci commit system

# set default theme
# uci set luci.main.mediaurlbase=/luci-static/argon
uci set luci.main.mediaurlbase=/luci-static/design
# uci set luci.main.mediaurlbase=/luci-static/material
uci commit luci

# detect network version
new_net=true
if [ -n "$(uci -q get network.lan.type)" ]; then
    new_net=false
fi

# network
uci delete network.globals.ula_prefix
uci delete network.wan
uci delete network.wan6

# lan
uci delete network.lan.ip6assign
uci set network.lan.ipaddr='10.12.2.188'
uci set network.lan.netmask='255.255.240.0'
uci set network.lan.gateway='10.12.2.1'
uci set network.lan.dns='223.5.5.5 114.114.114.114'

# lan6
uci set network.lan6=interface
uci set network.lan6.proto='dhcpv6'
if $new_net; then
    uci set network.lan6.device='@lan'
else
    uci set network.lan6.ifname='@lan'
fi
uci set network.lan6.reqaddress='try'
uci set network.lan6.reqprefix='auto'
uci set network.lan6.peerdns='0'

# add zerotier interface
if [ -f "/etc/config/zerotier" ]; then
    uci set network.zerotier=interface
    uci set network.zerotier.proto='none'
    if $new_net; then
        uci set network.zerotier.device='zt5u4x7t2c'
    else
        uci set network.zerotier.ifname='zt5u4x7t2c'
    fi
    uci set network.zerotier.delegate='0'
    uci set network.zerotier.auto='1'
fi

uci commit network

# dhcp
uci set dhcp.lan.ignore=1
uci delete dhcp.lan.start
uci delete dhcp.lan.limit
uci delete dhcp.lan.leasetime
uci delete dhcp.lan.dhcpv6
uci delete dhcp.lan.ra
uci commit dhcp

# disable redirect https
uci set uhttpd.main.redirect_https='0'
uci commit uhttpd

# remove feeds repository
sed -i '/helloworld/d' /etc/opkg/distfeeds.conf
sed -i '/passwall/d' /etc/opkg/distfeeds.conf
sed -i '/n2n/d' /etc/opkg/distfeeds.conf

# move menu
sed -i 's/\"services\"/\"control\"/g' /usr/lib/lua/luci/controller/appfilter.lua
sed -i 's/\"services\"/\"control\"/g' /usr/lib/lua/luci/controller/mia.lua

# anti-ad auto update for smartdns
# if [ -f "/etc/smartdns/anti-ad.sh" ]; then
#     echo "0 5 * * * /etc/smartdns/anti-ad.sh > /dev/null 2>&1 &" >>/etc/crontabs/root
# fi

# rules auto update for mosdns
if [ -f "/etc/mosdns/update_rules.sh" ]; then
    echo "0 6 * * * /etc/mosdns/update_rules.sh" >>/etc/crontabs/root
fi

# firewall.user
# NTP
# sed -i '/REDIRECT --to-ports 123/d' /etc/firewall.user
# echo "iptables -t nat -A PREROUTING -p udp --dport 123 -j REDIRECT --to-ports 123" >>/etc/firewall.user

# disable dnsmasq dns cache
uci set dhcp.@dnsmasq[0].dns_redirect='0'
uci set dhcp.@dnsmasq[0].cachesize='0'
uci set dhcp.@dnsmasq[0].server='127.0.0.1#5335'
# modify default port, adguardhome use 53
uci set dhcp.@dnsmasq[0].port='3553'
uci commit dhcp

# firewall
uci set firewall.@zone[0].network='lan lan6 zerotier'
uci set firewall.@zone[1].network='wan wan6'
uci commit firewall

# shadowsocksr
uci set shadowsocksr.@global[0].pdnsd_enable='0'
uci delete shadowsocksr.@global[0].tunnel_forward
uci commit shadowsocksr

# mosdns
uci set mosdns.config.enabled='1'
# uci set mosdns.config.redirect='1'
uci commit mosdns

uci commit

exit 0
